TARGET = solver 
OBJS = $(CPPS:.cpp=.o)
CPPS = $(wildcard *.cpp)
CXX = g++
CXXFLAGS = -Wall -O3

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) -Wl,--stack,16777216 -o $@ $(OBJS)

clean:
	rm *.o
	rm $(TARGET)
